# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sarahwbs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarahwbs/react-test npm run test

after_success:
  - docker build -t sarahwbs/multi-client ./client
  - docker build -t sarahwbs/multi-nginx ./nginx
  - docker build -t sarahwbs/multi-server ./server
  - docker build -t sarahwbs/multi-worker ./worker
