sudo: required
dist: focal
language: python
python:
  - "3.10"
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - echo "$GCP_SERVICE_ACCOUNT" | base64 --decode > service-account.json
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-493918
  - gcloud config set compute/region us-central1
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sarahwbs/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sarahwbs/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
